name: aws ip ranges
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denolib/setup-deno@v2
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://ip-ranges.amazonaws.com/ip-ranges.json
          downloaded_filename: aws-ip-ranges.json
          postprocess: ./postprocess.ts
